# Generated by Django 4.0.5 on 2022-07-13 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 20, 20, 14, 114424, tzinfo=utc)),
        ),
    ]
